#!/bin/sh

phone="CX75sw13"
outname="ElfPack_"$phone".vkp"
swilibBegin="+0FD4000"
AddrLibrary="03FC: 0xA0FD4000"
directory=${PWD}


cd ../../
./postbuild "$directory" "$phone" "$outname" "$swilibBegin" "$AddrLibrary"

exit 0
