#!/bin/sh

phone="CF75sw23"
outname="ElfPack_"$phone".vkp"
swilibBegin="+10E4000"
AddrLibrary="03FC: 0xA10E4000"
directory=${PWD}


cd ../../
./postbuild "$directory" "$phone" "$outname" "$swilibBegin" "$AddrLibrary"

exit 0
