#!/bin/sh

phone="CF75sw23"
outname="ElfPack_"$phone".vkp"

wine ../../elf2vkp.exe ELFLoader.elf ElfLoader3.vkp ff.bin &> /dev/null

echo ";"$phone > $outname
cat ../../copyright.txt >> $outname
echo "#pragma enable old_equal_ff" >> $outname
cat ElfLoader3.vkp >> $outname
echo "" >> $outname
echo " ; Needed function" >> $outname
echo "+10E4000" >> $outname
echo "03FC: 0xA10E4000   ;  FF: unsigned int AddrLibrary()" >> $outname
echo "+0" >> $outname
echo "#pragma disable old_equal_ff" >> $outname

exit 0
