#!/bin/sh

phone="C75sw24"
outname="ElfPack_"$phone".vkp"
swilibBegin="+10E4000"
AddrLibrary="3FC: 0xA10E4000"
directory=${PWD}


cd ../../
./postbuild "$directory" "$phone" "$outname" "$swilibBegin" "$AddrLibrary"

exit 0
