#!/bin/sh

phone="CX70sw56"
outname="ElfPack_"$phone".vkp"
swilibBegin="+0FC0000"
AddrLibrary="03FC: 0xA0FC0000"
directory=${PWD}


cd ../../
./postbuild "$directory" "$phone" "$outname" "$swilibBegin" "$AddrLibrary"

exit 0
