#!/bin/sh

phone="S75sw40"
outname="ElfPack_"$phone".vkp"

wine ../../elf2vkp.exe ELFLoader.elf ElfLoader3.vkp &> /dev/null

echo ";"$phone > $outname
cat ../../copyright.txt >> $outname
echo "#pragma enable old_equal_ff" >> $outname
cat ElfLoader3.vkp >> $outname

exit 0
