#!/bin/sh

phone="S75sw40"
outname="ElfPack_"$phone".vkp"
swilibBegin="+0074000"
AddrLibrary="03FC: A0074000"
directory=${PWD}


cd ../../
./postbuild "$directory" "$phone" "$outname" "$swilibBegin" "$AddrLibrary"

exit 0
