#!/bin/sh

phone="S75sw47"
outname="ElfPack_"$phone".vkp"

wine ../../elf2vkp.exe ELFLoader.elf ElfLoader3.vkp &> /dev/null

echo ";"$phone > $outname
cat ../../copyright.txt >> $outname
cat ElfLoader3.vkp >> $outname

exit 0
