#!/bin/sh

phone="C81sw51"
outname="ElfPack_"$phone".vkp"
swilibBegin="+0074000"
AddrLibrary="03FC: 0xA0074000"
directory=${PWD}


cd ../../
./postbuild "$directory" "$phone" "$outname" "$swilibBegin" "$AddrLibrary"

exit 0
